apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-name
  namespace: api
spec:
  project: default
  source:
    repoURL: https://github.com/GoodGoodJM/cd-test.git
    targetRevision: HEAD
    path: api
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true