apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: api
        image: ghcr.io/wewoogo/api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: myapi