apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: nginx-container
        image: amsy810/echo-nginx:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: myapi